name: maps_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.3
  location: ^5.0.3
  permission_handler: ^11.0.1
  geolocator: ^9.0.2
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  geocoding: ^4.0.0
  flutter_polyline_points: ^3.0.1
  dio: ^5.8.0+1
  maps_toolkit: ^3.0.0
  android_intent_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/pngs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
